version: "3.0"
services:
  rabbitmq:
    build: ./rabbitmq
    hostname: vpn-proxy_server-rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management console port
      - "15692:15692" # RabbitMQ management console prometheus plugin port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"
      RABBITMQ_PLUGINS: "rabbitmq_prometheus"
    volumes:
      - ./rabbitmq_volume:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3